### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by drgrejuva** [Runisco/Mrrls-Item-Information-#1]
Neat addon!  I get this when mousing over a dungeon keystone:

Message:` Interface\AddOns\MrrlsItemInformation\mrrl.lua:18: bad argument #2 to 'strsplit' (string expected, got nil)
Time: Wed Jul 10 09:04:43 2019
Count: 3
Stack: Interface\AddOns\MrrlsItemInformation\mrrl.lua:18: bad argument #2 to 'strsplit' (string expected, got nil)
[C]: ?
Interface\AddOns\MrrlsItemInformation\mrrl.lua:18: in function <Interface\AddOns\MrrlsItemInformation\mrrl.lua:13>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: in function `SetBagItem'
Interface\FrameXML\ContainerFrame.lua:1403: in function `ContainerFrameItemButton_OnEnter'
...AddOns\Bagnon\external\Wildpants\components\item.lua:371: in function `ShowTooltip'
...AddOns\Bagnon\external\Wildpants\components\item.lua:207: in function <...AddOns\Bagnon\external\Wildpants\components\item.lua:200>

Locals: (*temporary) = ":"
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by Runisco** [comment]
Would you mind trying to disable the bagnon addon, reload your ui, then try to mouseover the item again?

**Comment by drgrejuva** [comment]
Done. Here's the error:


Message: Interface\AddOns\MrrlsItemInformation\mrrl.lua:18: bad argument #2 to 'strsplit' (string expected, got nil)
Time: Thu Jul 11 06:19:59 2019
Count: 2
Stack: Interface\AddOns\MrrlsItemInformation\mrrl.lua:18: bad argument #2 to 'strsplit' (string expected, got nil)
[C]: ?
Interface\AddOns\MrrlsItemInformation\mrrl.lua:18: in function <Interface\AddOns\MrrlsItemInformation\mrrl.lua:13>
[C]: ?
[C]: ?
[C]: ?
[C]: in function `SetBagItem'
Interface\FrameXML\ContainerFrame.lua:1403: in function `ContainerFrameItemButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals: (*temporary) = ":"
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by Runisco** [comment]
Thank you. Could you please download this file, and unpack it to your wow interface folder, making sure to overwrite when it asks too.
[MrrlsItemInformation_1.1.0a.zip](https://github.com/Runisco/Mrrls-Item-Information-/files/3381317/MrrlsItemInformation_1.1.0a.zip)

**Comment by drgrejuva** [comment]
It does appear to work! No more errors on mousing over the keystone. Thanks.

Something else I just noticed: There's no added tooltip on Mrrl's special item today (Ominous Looking Tome).

**Comment by Runisco** [comment]
I know, I didn't add it at the time because it had a use effect described on it. But when I was playing I saw it didn't explain much. 

So I've already added that item, which will be included in the newest version which I am about to upload. Thank you for your help :)
